version: "3.9"

services:
  app1:
    build: .
    environment:
      - NODE_ID=node1
    ports:
      - "5001:5000"

  app2:
    build: .
    environment:
      - NODE_ID=node2
    ports:
      - "5002:5000"


